# Generated by Django 4.1.3 on 2022-11-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='zero', max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('mood', models.CharField(default='neutral', max_length=10)),
                ('date', models.DateField()),
                ('reason', models.CharField(default='lorem ipsum dolor sit amet', max_length=255)),
            ],
        ),
    ]
