# Generated by Django 4.1.3 on 2022-11-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='date',
        ),
    ]
